CREATE TABLE IF NOT EXISTS redes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  activo INT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS grupos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  red_id INT NOT NULL,
  nombre TEXT NOT NULL,
  dia_habitual TEXT,
  hora_habitual TEXT,
  duracion_habitual TEXT,
  direccion TEXT,
  barrio TEXT,
  ciudad TEXT,
  referencia TEXT,
  activo INT NOT NULL DEFAULT 1,
  FOREIGN KEY (red_id) REFERENCES redes(id)
);

CREATE TABLE IF NOT EXISTS personas (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_completo TEXT NOT NULL,
  cedula TEXT,
  fecha_nacimiento TEXT,
  sexo TEXT,
  celular TEXT,
  direccion TEXT,
  barrio TEXT,
  ciudad TEXT,
  estado_civil TEXT,
  fecha_llegada_grupo TEXT,
  bautizado INT NOT NULL DEFAULT 0,
  fecha_bautismo TEXT,
  en_discipulado INT NOT NULL DEFAULT 0,
  nivel_discipulado TEXT,
  es_nuevo INT NOT NULL DEFAULT 0,
  activo INT NOT NULL DEFAULT 1,
  observaciones TEXT
);

CREATE TABLE IF NOT EXISTS persona_red (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  persona_id INT NOT NULL,
  red_id INT NOT NULL,
  fecha_inicio TEXT,
  fecha_fin TEXT,
  activo INT NOT NULL DEFAULT 1,
  FOREIGN KEY (persona_id) REFERENCES personas(id),
  FOREIGN KEY (red_id) REFERENCES redes(id)
);

CREATE TABLE IF NOT EXISTS persona_grupo (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  persona_id INT NOT NULL,
  grupo_id INT NOT NULL,
  rol TEXT NOT NULL CHECK (rol IN ('Líder', 'Apoyo', 'Anfitrión', 'Integrante')),
  fecha_inicio TEXT,
  fecha_fin TEXT,
  activo INT NOT NULL DEFAULT 1,
  FOREIGN KEY (persona_id) REFERENCES personas(id),
  FOREIGN KEY (grupo_id) REFERENCES grupos(id)
);

CREATE TABLE IF NOT EXISTS usuarios (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cedula TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  rol TEXT NOT NULL CHECK (rol IN ('Administrador', 'Pastor', 'Líder de Red', 'Líder de Grupo', 'Miembro')),
  persona_id INT UNIQUE,
  activo INT NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (persona_id) REFERENCES personas(id)
);

CREATE TABLE IF NOT EXISTS sesiones (
  token TEXT PRIMARY KEY,
  usuario_id INT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE IF NOT EXISTS reuniones (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grupo_id INT NOT NULL,
  fecha TEXT NOT NULL,
  tipo TEXT NOT NULL DEFAULT 'Grupo habitual' CHECK (tipo IN ('Grupo habitual', 'Servicio de red', 'Actividad especial', 'Reunión cancelada')),
  realizada INT NOT NULL DEFAULT 1,
  duracion TEXT,
  observacion TEXT,
  FOREIGN KEY (grupo_id) REFERENCES grupos(id)
);

CREATE TABLE IF NOT EXISTS asistencia_reunion (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reunion_id INT NOT NULL,
  persona_id INT NOT NULL,
  asistio INT NOT NULL DEFAULT 1,
  UNIQUE (reunion_id, persona_id),
  FOREIGN KEY (reunion_id) REFERENCES reuniones(id),
  FOREIGN KEY (persona_id) REFERENCES personas(id)
);

CREATE TABLE IF NOT EXISTS visitantes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reunion_id INT NOT NULL,
  nombre TEXT NOT NULL,
  telefono TEXT,
  observacion TEXT,
  FOREIGN KEY (reunion_id) REFERENCES reuniones(id)
);

CREATE TABLE IF NOT EXISTS proceso_formacion (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  persona_id INT NOT NULL,
  etapa TEXT NOT NULL CHECK (etapa IN ('Discípulo S1', 'Discípulo S2', 'Discípulo S3', 'Discípulo S4', 'Bendición N1', 'Bendición N2', 'Bendición N3', 'Ministerio de la Misericordia')),
  promedio REAL,
  fecha_inicio TEXT,
  fecha_fin TEXT,
  activo INT NOT NULL DEFAULT 1,
  UNIQUE (persona_id, etapa),
  FOREIGN KEY (persona_id) REFERENCES personas(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS unico_activo_formacion
  ON proceso_formacion (persona_id)
  WHERE activo = 1;